apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretNameDB }}
  namespace: {{ .Values.nameSpace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: SecretStore
  target:
    name: {{ .Values.global.secretNameDB }}
    creationPolicy: Owner
  data:
  {{- range .Values.dbSec }}
  - secretKey: {{ .sKey }}
    remoteRef:
      key: {{ .sManagerName }}
      property: {{ .sManagerKey }}
  {{- end }}
